### ISSUE TITLE
Music (mp3) is playing with "rauschen"

### ISSUE THREAD

**Issue by Dtrieb** [Paspartout/ogo-shell#4]
If you listen to a mp3 File the are "rauschen" noise in the background.
(Play with speaker)

**Comment by Paspartout** [comment]
Thank you for the report, and sorry for the late reply.

I suspect the noise coming from the internal audio DAC that drives the speaker.
Unfortunately I can't do much about this hardware limitation.

For me it happens mostly on quiet parts of songs. Would be nice if you can confirm that.
A solution for these could be offering volume levels >100%, or maybe some other volume normalization.
